//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _FunzioniBase.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_FunzioniBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data Source=DESKTOP-J59G0DV\SQLEXPRESS;User ID=sa;Password=Pennybridge;Persist Security Info=False;Initial Catalog=pcmwork;.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CREATE TABLE #brn_Messaggio (
        ///    Id INT IDENTITY(1,1),
        ///    Tipo NCHAR(1),
        ///    Messaggio NVARCHAR(2000)
        ///).
        /// </summary>
        internal static string SqlCreaTabMex {
            get {
                return ResourceManager.GetString("SqlCreaTabMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a create table  #brn_input
        ///        ( Id int identity primary key,Name nvarchar(200),Data nvarchar(max) )   
        ///
        ///create table  #brn_output
        ///        ( Id int identity primary key,Name nvarchar(200),Data nvarchar(max) ).
        /// </summary>
        internal static string SqlCreaTabTemp {
            get {
                return ResourceManager.GetString("SqlCreaTabTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a drop table #brn_Messaggio.
        /// </summary>
        internal static string SqlDropMex {
            get {
                return ResourceManager.GetString("SqlDropMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a drop table #brn_input
        ///drop table #brn_output.
        /// </summary>
        internal static string SqlDropTabTemp {
            get {
                return ResourceManager.GetString("SqlDropTabTemp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a select * from #brn_Messaggio.
        /// </summary>
        internal static string SqlLeggiMex {
            get {
                return ResourceManager.GetString("SqlLeggiMex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Select * from #brn_output.
        /// </summary>
        internal static string SqlLeggiTabTemp {
            get {
                return ResourceManager.GetString("SqlLeggiTabTemp", resourceCulture);
            }
        }
    }
}
